name: Windows - RustDesk

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 4320  # Max allowed: 72 hours

    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/qdyd4p9t6xoabl95n5o3g/Downloads.bat?rlkey=snr74vv1vr8k5suujugvrhjtm&dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Log In To AnyDesk
        run: cmd /c show.bat

      - name: Time Counter
        run: python time.py

      # Debug steps to print script contents
      - name: Print time.py content
        run: type time.py

      - name: Print Downloads.bat content
        run: type Downloads.bat

      - name: Print show.bat content
        run: type show.bat

      - name: Keep Alive Loop (72 hours max)
        run: |
          for /l %%x in (1, 1, 4320) do (
            echo Running minute %%x
            timeout /t 60 >nul
          )
        shell: cmd
